CLASS zcl_lab_02_arith_sripizarro DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  INTERFACES if_oo_adt_classrun.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAB_02_ARITH_SRIPIZARRO IMPLEMENTATION.


METHOD if_oo_adt_classrun~main.
*1) SUMA
DATA: LV_BASE_RATE            TYPE i VALUE 20,
      LV_CORP_AREA_RATE       TYPE i VALUE 10,
      LV_MEDICAL_SERVICE_RATE TYPE i VALUE 15,
      LV_TOTAL_RATE           TYPE i.

LV_MEDICAL_SERVICE_RATE = LV_BASE_RATE + LV_CORP_AREA_RATE + LV_MEDICAL_SERVICE_RATE.
ADD 5 TO LV_MEDICAL_SERVICE_RATE.

*2) RESTA
LV_TOTAL_RATE = LV_TOTAL_RATE - 4.

*3) MULTIPLICACION
DATA: LV_MAINTENANCE_RATE TYPE i VALUE 2,
      LV_COST_PER_KG      TYPE i VALUE 3,
      LV_MULTI_RATE       TYPE i.

LV_MULTI_RATE = 2.

*4) DIVISION
DATA: LV_TOTAL_WEIGHT TYPE i VALUE 33,
      LV_NUM_PACKAGES TYPE i VALUE 4,
      LV_APPLIED_RATE TYPE p LENGTH 8 DECIMALS 2.

LV_APPLIED_RATE = LV_TOTAL_WEIGHT / LV_NUM_PACKAGES.

*5) DIV. SIN RESTO / SERNTENCIA DIV
DATA: LV_TOTAL_COST         TYPE i VALUE 19,
      LV_DISCOUNT_THRESHOLD TYPE i VALUE 4,
      LV_RESULT             TYPE p LENGTH 4 DECIMALS 2,
      LV_REMAINDER          TYPE p LENGTH 4 DECIMALS 2.

LV_RESULT = LV_TOTAL_COST DIV LV_DISCOUNT_THRESHOLD.
out->write( LV_RESULT ).

*6) RESTO / SERNTENCIA MOD
LV_REMAINDER = LV_TOTAL_COST MOD LV_DISCOUNT_THRESHOLD.
out->write( LV_REMAINDER ).

*7) EXPONENCIACION
DATA: LV_WEIGHT      TYPE i VALUE 5,
      LV_EXPO        TYPE I,
      LV_SQUARE_ROOT TYPE i.

LV_EXPO = LV_WEIGHT ** 2.

*8) RAIZ CUADRADA

LV_SQUARE_ROOT = SQRT( LV_EXPO ).




ENDMETHOD.
ENDCLASS.
